name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.github.com/repos/nf-core/methylseq/contributors
          downloaded_filename: methylseq_contributors.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://slack.com/api/team.billableInfo?token=$config['slack_access_token&pretty=1
          downloaded_filename: slack.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.github.com/repos/nf-core/methylseq/traffic/views
          downloaded_filename: methylseq_views.json
